language: minimal
dist: xenial
services:
  - docker

before_install:
  - curl https://raw.githubusercontent.com/plicease/cip/main/bin/travis-bootstrap | bash
  - cip before-install

install:
  - cip diag
  - cip install

script:
  - cip script

jobs:
  include:
    - env: CIP_TAG=static
    - env: CIP_TAG=5.33
    - env: CIP_TAG=5.32

branches:
  only:
    - main

cache:
  directories:
    - "$HOME/.cip"
